### ISSUE TITLE
Power-Shell Syntax Incorrect

### ISSUE THREAD

**Issue by HillJamison1** [jmarrec/Pry-and-Powershell-for-OpenStudio#1]
Julien, maybe this is a problem with Power-Shell 3, but to create a new profile you need use the following line:
New-Item -Path $profile -ItemType "file" -Force
The original command you provided in the ReadMe does not work

**Comment by jmarrec** [comment]
Interesting. I had tried to do a clean install on another computer a month back, and that definitely worked for me.

Can you type `$PSVersionTable.PSVersion` in Power shell and let me know what comes out? Mine is

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  494
```

**Comment by HillJamison1** [comment]
Same as you.

Major  Minor  Build  Revision

---

5      0      10586  494
