### ISSUE TITLE
Issue installing Development kit

### ISSUE THREAD

**Issue by antonszilasi** [jmarrec/Pry-and-Powershell-for-OpenStudio#2]
@jmarrec 

Many thanks for putting together this development environment it looks very useful! Unfortunately I am having trouble installing pry-theme. The development kit more specifically.

I followed the instructions to install the development environment here: https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

I've written my config file to contain

![config](https://cloud.githubusercontent.com/assets/8773483/21234879/193820d8-c2ba-11e6-8349-164ab1795eae.JPG)

If I run ruby dk.rb review in the Development kit directory I get the following:

![rb dk install](https://cloud.githubusercontent.com/assets/8773483/21234848/ef6a9588-c2b9-11e6-906e-7d73f80877fe.JPG)

Clearly the DevKit is picking up Ruby installed on my machine. However when I run 

ruby dk.rb install, I get the following:
![rb dk install](https://cloud.githubusercontent.com/assets/8773483/21155832/4fb82d06-c139-11e6-94fa-2638e43f0c68.JPG)

Do you have any ideas?

**Comment by jmarrec** [comment]
Hey Anton, this isn't an issue that's directly related to this repo but rather a general one on installing the DevKit. Anyways, I'll try to help :)

Open your `config.yml` that was created when you ran the `ruby dk.rb`. Try to remove the `C:/Program Files/OpenStudio...` ruby and rerun it. Also make sure that the `C:/Ruby200-x64` is right, and that the path uses forward slashes (`C:/` not `C:\`).

If that still doesn't solve it, you should search on stackoverflow ([this post](http://stackoverflow.com/questions/18803223/unable-to-find-rubygems-in-site-ruby-or-core-ruby) for example)
